version: 2.1
workflows:
  version: 2
  main:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint-src:
          name: "Lint Src"
          requires:
            - install
      - lint-docs:
          name: "Lint Docs"
          requires:
            - install
      - test-unit-cli:
          name: "Unit Test CLI Src"
          requires:
            - install
      - test-unit-core:
          name: "Unit Test Core Src"
          requires:
            - install   
      - test-unit-node:
          name: "Unit Test Node Src"
          requires:
            - install
      - test-unit-browser:
          name: "Unit Test Browser Src"
          requires:
            - install
      - test-unit-requester-utils:
          name: "Unit Test Requester-Utils Src"
          requires:
            - install

jobs: 
  #Link and Install all required dependancies
  install:
    docker:
      - image: node:lts
    environment:
        PLAYWRIGHT_BROWSERS_PATH: 0
    steps:
      - checkout
      - run: yarn
      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  build:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn build
      - store_artifacts:
          path: packages/core/dist/
      - store_artifacts:
          path: packages/cli/dist/
      - store_artifacts:
          path: packages/node/dist/
      - store_artifacts:
          path: packages/browser/dist/
      - store_artifacts:
          path: packages/requester-utils/dist/

  # Lint all code, tests and supporting documentation (README, CHANGELOG etc)
  lint-src:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn lint

  lint-docs:
      docker:
        - image: node:lts-alpine
      steps:
        - checkout
        - restore_cache:
            name: Restore yarn package cache
            keys:
              - yarn-packages-{{ checksum "yarn.lock" }}
        - run: yarn lint

  test-unit-cli:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn workspace @gitbeaker/core test:unit && yarn codecov -F core

  test-unit-core:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn workspace @gitbeaker/core test:unit && yarn codecov -F core

  test-unit-node:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn workspace @gitbeaker/node test:unit && yarn codecov -F core

  test-unit-browser:
    docker:
      - image: mcr.microsoft.com/playwright:bionic
    environment:
        PLAYWRIGHT_BROWSERS_PATH: 0
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn workspace @gitbeaker/core test:unit && yarn codecov -F core

  test-unit-requester-utils:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn workspace @gitbeaker/requester-utils test:unit && yarn codecov -F core
